"""empty message

Revision ID: 89a562c12762
Revises: 7d370809c988
Create Date: 2022-05-31 14:27:40.583520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a562c12762'
down_revision = '7d370809c988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('looking_for_venue', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'looking_for_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
